### ISSUE TITLE
Optimize loadFromSku method to use static cache & functions calling getAttributeValue to load SKU object.

### ISSUE THREAD

**Issue by piyuesh23** [acquia/commerce-manager#12]

**Comment by piyuesh23** [comment]
Pull request to fix this one: https://github.com/acquia/commerce-manager/pull/13

**Comment by nikunjkotecha** [comment]
PR to fix without breaking existing method definition #26

**Comment by nikunjkotecha** [comment]
@piyuesh23 @miromichalicka we can close this one, PR is merged.
