### ISSUE TITLE
Check if parent node exists for the items added in cart.

### ISSUE THREAD

**Issue by joshirohit100** [acquia/commerce-manager#14]
We are adding skus in the cart and then on cart page, we just simply checks for the parent/display node (product) for that sku but there are chances that for a sku added in cart, parent/display node is removed from BE and in this case it just breaks.

Even the SKUPluginInterface::getDisplayNode() defination says that this might return NULL but then we using this without any check.

**Comment by joshirohit100** [comment]
PR is raised for the same #15 .

**Comment by miromichalicka** [comment]
Fixed in #15
