### ISSUE TITLE
Allow setting product title based on Brand specific logic.

### ISSUE THREAD

**Issue by nikunjkotecha** [acquia/commerce-manager#54]
We need to allow setting title of configurable product based on selected variant. This (if we do) should be done on multiple pages
* Product detail page (we already have AJAX triggered when user selects a configurable option)
* Cart object (cart/checkout pages)
* Order detail

Suggested approach:
* We can introduce a new event in acm_sku which would be responsible to provide the brand specific info (title for our case).
* Default value can be very simple and part of code that is dispatching event
* Service to dispatch the event and provide value (we can send field name or identifier as second argument and context as third - getValue($sku, 'title', $value, 'cart') for instance, this would allow us to use for all different fields 

Helper service can have
- getValue()
- getTitle($sku, $context) => getValue($sku, 'title', $value, $context)
- getDescription($sku, $context) => getValue($sku, 'description', $value, $context)
- getFirstImage() => ...
- getGallery() => ...

getValue here will be responsible for dispatching event and get updated value
specific functions here will be responsible for simplest default values

$context here can be service class constants 
- Listing
- Detail
- Basket_Order

**Comment by nikunjkotecha** [comment]
@miromichalicka @sdelbosc @vbouchet31 

does the approach here look good?

**Comment by miromichalicka** [comment]
@nikunjkotecha I think that firing new event would be the best approach. What do you think?

**Comment by nikunjkotecha** [comment]
sure, makes sense, updating description

**Comment by nikunjkotecha** [comment]
@miromichalicka @sdelbosc @vbouchet31 updated description, please review once now

**Comment by miromichalicka** [comment]
@nikunjkotecha sounds good, I'm just wondering, what needs to be a part of this module. I think that most people won't need to modify it, so firing an event should be enough?

**Comment by nikunjkotecha** [comment]
@miromichalicka yes firing event should be enough and we can implement for title and/or description here as those are most commonly used, we can think of image later (for sure not part of this request/pr)

Idea is to provide a base to allow extending ACM code

**Comment by miromichalicka** [comment]
cool, sounds good for me

**Comment by nikunjkotecha** [comment]
PR: https://github.com/acquia/commerce-manager/pull/72
